In [40]:
print ("Hello, Machine Learning!")

Hello, Machine Learning!


In [41]:
age = 9
height = 1.4
print (age, 
       height)

9 1.4


In [42]:
name = "Yusuf"
print (name)


Yusuf


In [43]:
is_student = True
print (is_student)

True


In [44]:
fruits = ["apple", "banana", "orange"]
print (fruits)

['apple', 'banana', 'orange']


Creating a List


In [45]:
colors = ["red", "blue", "green"]
print (colors)

['red', 'blue', 'green']


In [46]:
print(colors[0])

red


In [47]:
print(colors[1])

blue


Tuple: ordered,immutable, written with parenthesis

In [48]:
birth_year = (2015,)
print(birth_year)

(2015,)


In [49]:
point = (3, 5)
print (point)

(3, 5)


Dictionary: key -> value pairs, accessed using keys, written with curly braces

In [50]:
student = {
    "name": "Yusuf",
    "age": 9,
    "height": 1.4,
    "is_student": True
}
print (student)

{'name': 'Yusuf', 'age': 9, 'height': 1.4, 'is_student': True}


In [51]:
print(student["name"])
print(student["age"])

Yusuf
9


In [52]:
car = {"brand": "Toyota", "year": 2020}
print(car["brand"])

Toyota


conditionals: if, else, elif

In [53]:
age = 9

if age >= 5:
    print("You are eligible for school.")
else:
    print("You are too young")

You are eligible for school.


In [54]:
is_raining = False

if is_raining:
    print("Take an umbrella.")
else:
    print("No umbrella needed")

No umbrella needed


In [55]:
score = 75

if score >= 90:
    print("Excellent")
elif score >= 60:
    print("Good")
else:
    print("Try again")

Good


In [56]:
age = 3

if age > 5:
    print(School)
else:
    print("Home")


Home


Basic For Loop Structure

In [57]:
for item in something:
    do something

SyntaxError: invalid syntax (14338427.py, line 2)

In [ ]:
for number in [1, 2, 3]:
    print(number)

1
2
3


In [ ]:
fruits = ["apple", "banana", "orange"]
for fruit in fruits:
    print(fruit)

apple
banana
orange


Loop with counting

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in range(3):
    print("Hello")

Hello
Hello
Hello


In [ ]:
for animal in ["cat", "dog"]:
    print(animal)

cat
dog


FUNCTIONS: 
A FUNCTION IS A NAMED BLOCKED CODE
IT CAN INPUTS
IT CAN GIVE BACK OUTPUTS
IT HELPS AVOID REPEATING CODES

In [ ]:
def functinos_name(inputs):
    do something
    return result


In [ ]:
def say_hello():
    print("Hello!")

say_hello()

Hello!


In [ ]:
def greet(name):
    print("Hello", name)

In [ ]:
greet("Yerimah")

Hello Yerimah


FUNTION WITH OUTPUT

In [ ]:
def add(a,b):
    return a + b

result = add(2,3)
print(result)

5


In [ ]:
def double(x):
    return x * 2
print(double(4))

8


WHY FUNCTIONS MATTERS FOR MACHINE LEARNING
- MODELS ARE FUNCTION 
- TRAINING IS A FUNCTION
- PREDICTION IS A FUNCTION

NumPy:
- NumPy is a Python library for fast numerical computation
- It introduces the ndarray
- Arrays are:
 - Fixed-type
 - Fast
 - Vectorized (operate on many values at once)

This is the backbone of ML math

In [ ]:
import numpy as np
np.__version__


'2.4.0'

In [ ]:
print(np.array([1,2,3]))


[1 2 3]


In [ ]:
scores = np.array([50, 60,70,80])
print(scores)

[50 60 70 80]


In [ ]:
# indexing a NunPy array
print(scores[0])
print(scores[1])

50
60


In [ ]:
# 2-D NumPy array (A Table)

marks = np.array([
    [50,60,70],
    [80,90,100]
])

print(marks)

[[ 50  60  70]
 [ 80  90 100]]


In [ ]:
# Getting values from a table
print(marks[0])
print(marks[0][1])
print(marks[1, 2])

[50 60 70]
60
100


In [ ]:
# shapes

print(marks.shape)

(2, 3)


In [ ]:
# Math On Arrays (No Loops)

marks_plus_5 = marks + 5
print(marks_plus_5)

[[ 55  65  75]
 [ 85  95 105]]


NumPy SUPERPOWER: BROADCASTING

Broadcasting means NumPy automatically stretches numbers

A single number can be applied to:

A row

A column

A whole table

Shapes must be compatible

In [ ]:
scores = np.array([50,60,70])
print(scores + 10)

[60 70 80]


In [ ]:
marks = np.array([
    [50,60],
    [70,80]
])

print(marks + 5)

[[55 65]
 [75 85]]


In [ ]:
# Row Broadcasting

bonus = np.array([5,10])
print(marks + bonus)

[[55 70]
 [75 90]]


In [ ]:
print(marks.shape)
print(bonus.shape)

(2, 2)
(2,)


In [ ]:
np.array([1,2,3]) + 1

array([2, 3, 4])

UNDERSTANDING DATA WITH NUMPY 

(MEAN, SUM, MIN, MAX)

In [ ]:
import numpy as np
scores = np.array([50,60,70,80,90])

In [ ]:
print(np.sum(scores))

350


In [ ]:
print(np.mean(scores))

70.0


In [ ]:
print(np.max(scores))
print(np.min(scores))

90
50


In [ ]:
# working with tables 2D-Arrays

marks = np.array([
    [50,60,70],
    [80,90,100]
])

In [ ]:
print(np.mean(marks))

75.0


In [ ]:
print(np.mean(marks, axis=1))

[60. 90.]


In [ ]:
print(np.mean(marks, axis=0))

[65. 75. 85.]


In [ ]:
data = np.array([[2,4], [6,8]])

In [ ]:
np.sum(data)

np.int64(20)

INTRODUCTION TO PANDAS

pandas is a Python library for data analysis

It introduces:

-Series (one column)

-DataFrame (full table)

Used for:

-Cleaning data

-Exploring data

-Preparing data for ML

Most ML datasets start in pandas.

In [ ]:
import pandas as pd
pd.__version__

data = {
    "name": ["Chichi", "Elena", "David"],
    "age": [9,10,9],
    "score": [80,90,85]
}

df = pd.DataFrame(data)
print(df)

     name  age  score
0  Chichi    9     80
1   Elena   10     90
2   David    9     85


In [ ]:
print(df.columns)

Index(['name', 'age', 'score'], dtype='object')


In [ ]:
print(df["score"])

0    80
1    90
2    85
Name: score, dtype: int64


In [ ]:
print(df.loc[0])

name     Chichi
age           9
score        80
Name: 0, dtype: object


In [ ]:
print(df.head())
print(df.info())

     name  age  score
0  Chichi    9     80
1   Elena   10     90
2   David    9     85
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
 2   score   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None


In [ ]:
print(df["score"].mean())
print(df["score"].max())

85.0
90


In [ ]:
df["age"]

0     9
1    10
2     9
Name: age, dtype: int64

FILTERING & SELECTING DATA (ASKING QUESTIONS)

How to select columns

How to filter rows

How to ask simple questions like “Who scored above 80?”

In [ ]:
import pandas as pd

data = {
    "name": ["Yusuf", "Chichi", "David", "Elena"],
    "age": [9, 10, 9, 11],
    "score": [80, 90, 75, 95]
}

df = pd.DataFrame(data)
df


name  age  score
0   Yusuf    9     80
1  Chichi   10     90
2   David    9     75
3   Elena   11     95

In [ ]:
df["score"]


0    80
1    90
2    75
3    95
Name: score, dtype: int64

In [ ]:
df [["name", "score"]]

name  score
0   Yusuf     80
1  Chichi     90
2   David     75
3   Elena     95

In [ ]:
df [df["score"]> 80]

name  age  score
1  Chichi   10     90
3   Elena   11     95

In [ ]:
df[df["age"]> 9]

name  age  score
1  Chichi   10     90
3   Elena   11     95

In [ ]:
# Combining conditions

df[(df["age"]> 9) & (df["score"]> 85)]

name  age  score
1  Chichi   10     90
3   Elena   11     95

SORTING DATA & ADDING NEW COLUMNS (FEATURE CREATION)

How to sort data

How to add new columns

How machines create new information from old data

In [ ]:
import pandas as pd
df.sort_values(by="score")

name  age  score
2   David    9     75
0   Yusuf    9     80
1  Chichi   10     90
3   Elena   11     95

In [ ]:
#score from highest to lowest
df.sort_values(by="score", ascending=False)

name  age  score
3   Elena   11     95
1  Chichi   10     90
0   Yusuf    9     80
2   David    9     75

In [ ]:
#score from lowest to highest
df.sort_values(by="score", ascending=True)

name  age  score
2   David    9     75
0   Yusuf    9     80
1  Chichi   10     90
3   Elena   11     95

In [ ]:
#Adding a new column
df["pass"] = df["score"] >= 80
df

name  age  score   pass
0   Yusuf    9     80   True
1  Chichi   10     90   True
2   David    9     75  False
3   Elena   11     95   True

MACHINE LEARNING

The 3 main types of ML: SUPERVISED, UNSUPERVISED AND REINFORCED LEARNING

What supervised learning is

The difference between classification and regression

SUPERVISED LEARNING: TWO TYPES

A. Classification (LABELS[CATEGORY])

Output is a category

Examples:

Pass / Fail

Spam / Not spam

Yes / No


B. Regression (NUMBERS)

Output is a number

Examples:

House price

Temperature

Salary

FEATURES vs LABELS (FRAMING ML PROBLEMS CORRECTLY)

Clearly identify features

Clearly identify labels

Correctly frame a Machine Learning problem

If you get this wrong, models fail even with good code.

VERY IMPORTANT RULE

If the model already knows it before predicting → Feature

If the model is trying to predict it → Label

TRAINING DATA vs TEST DATA (AVOIDING CHEATING)

This is another critical concept. Many ML models fail because this is misunderstood.

Training data: Used to teach the model

Test data: Used to evaluate how well the model learned

The test data must be unseen during training

WHY WE SPLIT DATA

If you train and test on the same data:

Model looks perfect

But fails in real life

This is called overfitting.

| Term           | Meaning                |
| -------------- | ---------------------- |
| Training set   | Learning               |
| Test set       | Evaluation             |
| Overfitting    | Memorizing             |
| Generalization | Doing well on new data |


MODEL EVALUATION & ACCURACY

This is where Machine Learning stops being theory and starts being measurable.

Model evaluation measures how well predictions match real answers

Accuracy = correct predictions ÷ total predictions

WHY ACCURACY CAN LIE (VERY IMPORTANT)

Example: Spam Emails

95 emails are not spam

5 emails are spam

If a model says:

“Everything is not spam”

A high accuracy does not always mean a good model.

We must always understand:

The data

The problem

The consequences of mistakes

| Term            | Meaning               |
| --------------- | --------------------- |
| Accuracy        | Overall correctness   |
| Class imbalance | Unequal labels        |
| Evaluation      | Judging model quality |


CONFUSION MATRIX (UNDERSTANDING MISTAKES)

A confusion matrix is just a scoreboard that counts:

How many times you were right

How many times you were wrong

How you were wrong


THE FOUR POSSIBLE OUTCOMES

For a Yes / No problem (like Spam / Not Spam):

| Name                | What it means                        |
| ------------------- | ------------------------------------ |
| True Positive (TP)  | You said **Yes**, and it **was Yes** |
| True Negative (TN)  | You said **No**, and it **was No**   |
| False Positive (FP) | You said **Yes**, but it **was No**  |
| False Negative (FN) | You said **No**, but it **was Yes**  |


PRECISION & RECALL (QUALITY OF PREDICTIONS)

PRECISION (HOW CAREFUL YOU ARE)

Precision answers:
When the model says YES, how often is it correct?

RECALL (HOW MUCH YOU CATCH)

Recall answers:
Out of all real YES cases, how many did we catch?

SIMPLE EXAMPLE (SPAM)

Model flags 10 emails as spam

Only 7 are actually spam

➡ Precision = low (many false positives)

There were 20 spam emails total

Model caught only 7

➡ Recall = low (many missed spam)

WHEN EACH ONE MATTERS (VERY IMPORTANT)

| Situation         | More Important |
| ----------------- | -------------- |
| Spam filter       | Precision      |
| Disease detection | Recall         |
| Fraud detection   | Recall         |
| Recommendations   | Precision      |


PRECISION vs RECALL TRADE-OFF (WHY MODELS CAN’T BE PERFECT)

This is where ML becomes realistic.

Imagine a guard checking students:

If the guard is very strict:

Few wrong people enter

But some real students are blocked

If the guard is very relaxed:

All students enter

But some strangers enter too

You must choose how strict to be.

That choice is the threshold.

THE TRADE-OFF (CORE IDEA)

Higher threshold:

 ↑ Precision

 ↓ Recall

Lower threshold:

 ↓ Precision

 ↑ Recall

You cannot maximize both at the same time.

Model outputs a cancer risk score:

0.0 → no risk

1.0 → high risk

If threshold = 0.9:

Very few false alarms

Many missed cases

If threshold = 0.3:

Catch almost all cancer

Many false alarms

WHY THIS MATTERS IN REAL LIFE

Medicine → prioritize recall

Spam → prioritize precision

Fraud → prioritize recall

ML decisions affect people, not just numbers.

UNDERFITTING vs OVERFITTING (BIAS & VARIANCE)

This is a core concept in Machine Learning.

Learning to Shoot a Ball 🎯

Underfitting: (Model is too simple, learn too little)

You barely practice → you miss a lot

Overfitting: (Model is too complex, memorize training data)

You memorize one exact spot → you miss everywhere else

Good fit: (Learns patterns that generalize)

You practice enough → you hit most targets

| Term           | Meaning                      |
| -------------- | ---------------------------- |
| Bias           | Error from being too simple  |
| Variance       | Error from being too complex |
| Generalization | Works on new data            |


| Situation                  | Problem       |
| -------------------------- | ------------- |
| Poor training + poor test  | Underfitting  |
| Great training + poor test | Overfitting   |
| Good training + good test  | Healthy model |

WHY THIS MATTERS

Overfitted models fail in real life

Underfitted models are useless

Balance is the goal of ML